### ISSUE TITLE
Completed posts not being removed from the queue

### ISSUE THREAD

**Issue by Pf441** [GrafeasGroup/tor_archivist#16]
Looking at the "Filter by Flair" posts, some posts marked "Completed!" stay on the queue indefinitely, instead of being removed by the bot (even after weeks). r/antiMLM posts seem more likely to be affected by this bug, but it could be related to specific transcribers completing transcriptions in a critical period for the bot.

**Comment by NGTmeaty** [comment]
So looking at the filter by flair, I see [a ton of posts](https://owo.whats-th.is/9x692YF.png) but I question if they really are undeleted because if you look at the screenshot I put below, it shows we have exactly 1000, none of which are older than 16 hours, which is how the bot works, so I imagine this is just some weird reddit issue where it thinks it's not deleted, but it is.

![](https://owo.whats-th.is/9x2ezo5.png)

**Comment by Pf441** [comment]
I think the 1000 posts limit is due to Reddit limitations (there is the same with PRAW), so it could be this thing you've come across. If you filter by "In Progress", you can find months old posts.

**Comment by NGTmeaty** [comment]
I'm not actually sure, but I think the 1000 post limit is because of [how tor_archivist is setup](https://github.com/GrafeasGroup/tor_archivist/blob/master/tor_archivist/main.py#L70)? And the search is pulling up actually deleted posts? edit (like a hour later): this seems to be quite odd. Looking more into this, some subs have different amounts of posts you can view, some subs are at 950, some in the lower 500s, but looking at actual ToR "removed" posts, the main indicator that posts are removed is the "can_gild" property and that seems to be valid still on all the ToR posts I checked that were completed? So I'm no longer sure if it's actually deleting them correctly. But I do see the 1000 things limit on reddit's side.

**Comment by TheLonelyGhost** [comment]
It's very likely we didn't ever expect to have more than 1000 posts available at any given point. The tor_archivist bot is built by iterating through all posts versus tor is built to be event-driven. As a result tor_archivist scales far worse than tor does, but we have hopes that the shift to using blossom as a source of truth will help with that.
